apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-pvc
  namespace: {POD NAMESPACE}
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: docker-pvc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Gi
      
